#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Ecommerce")]
	public partial class BDEcommerceDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTBLCATEGORIA(TBLCATEGORIA instance);
    partial void UpdateTBLCATEGORIA(TBLCATEGORIA instance);
    partial void DeleteTBLCATEGORIA(TBLCATEGORIA instance);
    partial void InsertTBLCESTA(TBLCESTA instance);
    partial void UpdateTBLCESTA(TBLCESTA instance);
    partial void DeleteTBLCESTA(TBLCESTA instance);
    partial void InsertTBLCLIENTE(TBLCLIENTE instance);
    partial void UpdateTBLCLIENTE(TBLCLIENTE instance);
    partial void DeleteTBLCLIENTE(TBLCLIENTE instance);
    partial void InsertTBLCLIENTE_TBLCESTA(TBLCLIENTE_TBLCESTA instance);
    partial void UpdateTBLCLIENTE_TBLCESTA(TBLCLIENTE_TBLCESTA instance);
    partial void DeleteTBLCLIENTE_TBLCESTA(TBLCLIENTE_TBLCESTA instance);
    partial void InsertTBLCOMPRA(TBLCOMPRA instance);
    partial void UpdateTBLCOMPRA(TBLCOMPRA instance);
    partial void DeleteTBLCOMPRA(TBLCOMPRA instance);
    partial void InsertTBLCOMPRA_TBLITEMCOMPRA(TBLCOMPRA_TBLITEMCOMPRA instance);
    partial void UpdateTBLCOMPRA_TBLITEMCOMPRA(TBLCOMPRA_TBLITEMCOMPRA instance);
    partial void DeleteTBLCOMPRA_TBLITEMCOMPRA(TBLCOMPRA_TBLITEMCOMPRA instance);
    partial void InsertTBLDIRECCIONES(TBLDIRECCIONES instance);
    partial void UpdateTBLDIRECCIONES(TBLDIRECCIONES instance);
    partial void DeleteTBLDIRECCIONES(TBLDIRECCIONES instance);
    partial void InsertTBLIMPUESTOS(TBLIMPUESTOS instance);
    partial void UpdateTBLIMPUESTOS(TBLIMPUESTOS instance);
    partial void DeleteTBLIMPUESTOS(TBLIMPUESTOS instance);
    partial void InsertTBLITEMCOMPRA(TBLITEMCOMPRA instance);
    partial void UpdateTBLITEMCOMPRA(TBLITEMCOMPRA instance);
    partial void DeleteTBLITEMCOMPRA(TBLITEMCOMPRA instance);
    partial void InsertTBLMETODOPAGO(TBLMETODOPAGO instance);
    partial void UpdateTBLMETODOPAGO(TBLMETODOPAGO instance);
    partial void DeleteTBLMETODOPAGO(TBLMETODOPAGO instance);
    partial void InsertTBLPRODUCTOS(TBLPRODUCTOS instance);
    partial void UpdateTBLPRODUCTOS(TBLPRODUCTOS instance);
    partial void DeleteTBLPRODUCTOS(TBLPRODUCTOS instance);
    partial void InsertTBLPRODUCTOS_TBLCESTA(TBLPRODUCTOS_TBLCESTA instance);
    partial void UpdateTBLPRODUCTOS_TBLCESTA(TBLPRODUCTOS_TBLCESTA instance);
    partial void DeleteTBLPRODUCTOS_TBLCESTA(TBLPRODUCTOS_TBLCESTA instance);
    partial void InsertTBLROLES(TBLROLES instance);
    partial void UpdateTBLROLES(TBLROLES instance);
    partial void DeleteTBLROLES(TBLROLES instance);
    partial void InsertTBLCODRECUPERACION(TBLCODRECUPERACION instance);
    partial void UpdateTBLCODRECUPERACION(TBLCODRECUPERACION instance);
    partial void DeleteTBLCODRECUPERACION(TBLCODRECUPERACION instance);
    partial void InsertTBLUSUARIOS(TBLUSUARIOS instance);
    partial void UpdateTBLUSUARIOS(TBLUSUARIOS instance);
    partial void DeleteTBLUSUARIOS(TBLUSUARIOS instance);
    #endregion
		
		public BDEcommerceDataContext() : 
				base(global::Capa_Datos.Properties.Settings.Default.EcommerceConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BDEcommerceDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDEcommerceDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDEcommerceDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDEcommerceDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBLCATEGORIA> TBLCATEGORIA
		{
			get
			{
				return this.GetTable<TBLCATEGORIA>();
			}
		}
		
		public System.Data.Linq.Table<TBLCESTA> TBLCESTA
		{
			get
			{
				return this.GetTable<TBLCESTA>();
			}
		}
		
		public System.Data.Linq.Table<TBLCLIENTE> TBLCLIENTE
		{
			get
			{
				return this.GetTable<TBLCLIENTE>();
			}
		}
		
		public System.Data.Linq.Table<TBLCLIENTE_TBLCESTA> TBLCLIENTE_TBLCESTA
		{
			get
			{
				return this.GetTable<TBLCLIENTE_TBLCESTA>();
			}
		}
		
		public System.Data.Linq.Table<TBLCOMPRA> TBLCOMPRA
		{
			get
			{
				return this.GetTable<TBLCOMPRA>();
			}
		}
		
		public System.Data.Linq.Table<TBLCOMPRA_TBLITEMCOMPRA> TBLCOMPRA_TBLITEMCOMPRA
		{
			get
			{
				return this.GetTable<TBLCOMPRA_TBLITEMCOMPRA>();
			}
		}
		
		public System.Data.Linq.Table<TBLDIRECCIONES> TBLDIRECCIONES
		{
			get
			{
				return this.GetTable<TBLDIRECCIONES>();
			}
		}
		
		public System.Data.Linq.Table<TBLIMPUESTOS> TBLIMPUESTOS
		{
			get
			{
				return this.GetTable<TBLIMPUESTOS>();
			}
		}
		
		public System.Data.Linq.Table<TBLITEMCOMPRA> TBLITEMCOMPRA
		{
			get
			{
				return this.GetTable<TBLITEMCOMPRA>();
			}
		}
		
		public System.Data.Linq.Table<TBLMETODOPAGO> TBLMETODOPAGO
		{
			get
			{
				return this.GetTable<TBLMETODOPAGO>();
			}
		}
		
		public System.Data.Linq.Table<TBLPRODUCTOS> TBLPRODUCTOS
		{
			get
			{
				return this.GetTable<TBLPRODUCTOS>();
			}
		}
		
		public System.Data.Linq.Table<TBLPRODUCTOS_TBLCESTA> TBLPRODUCTOS_TBLCESTA
		{
			get
			{
				return this.GetTable<TBLPRODUCTOS_TBLCESTA>();
			}
		}
		
		public System.Data.Linq.Table<TBLROLES> TBLROLES
		{
			get
			{
				return this.GetTable<TBLROLES>();
			}
		}
		
		public System.Data.Linq.Table<TBLSMTP> TBLSMTP
		{
			get
			{
				return this.GetTable<TBLSMTP>();
			}
		}
		
		public System.Data.Linq.Table<TBLCODRECUPERACION> TBLCODRECUPERACION
		{
			get
			{
				return this.GetTable<TBLCODRECUPERACION>();
			}
		}
		
		public System.Data.Linq.Table<TBLUSUARIOS> TBLUSUARIOS
		{
			get
			{
				return this.GetTable<TBLUSUARIOS>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBLCATEGORIA")]
	public partial class TBLCATEGORIA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_CATEGORIA;
		
		private string _NOMBRE_CATEGORIA;
		
		private char _ESTADO_CATEGORIA;
		
		private EntitySet<TBLPRODUCTOS> _TBLPRODUCTOS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CATEGORIAChanging(int value);
    partial void OnID_CATEGORIAChanged();
    partial void OnNOMBRE_CATEGORIAChanging(string value);
    partial void OnNOMBRE_CATEGORIAChanged();
    partial void OnESTADO_CATEGORIAChanging(char value);
    partial void OnESTADO_CATEGORIAChanged();
    #endregion
		
		public TBLCATEGORIA()
		{
			this._TBLPRODUCTOS = new EntitySet<TBLPRODUCTOS>(new Action<TBLPRODUCTOS>(this.attach_TBLPRODUCTOS), new Action<TBLPRODUCTOS>(this.detach_TBLPRODUCTOS));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CATEGORIA", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_CATEGORIA
		{
			get
			{
				return this._ID_CATEGORIA;
			}
			set
			{
				if ((this._ID_CATEGORIA != value))
				{
					this.OnID_CATEGORIAChanging(value);
					this.SendPropertyChanging();
					this._ID_CATEGORIA = value;
					this.SendPropertyChanged("ID_CATEGORIA");
					this.OnID_CATEGORIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_CATEGORIA", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE_CATEGORIA
		{
			get
			{
				return this._NOMBRE_CATEGORIA;
			}
			set
			{
				if ((this._NOMBRE_CATEGORIA != value))
				{
					this.OnNOMBRE_CATEGORIAChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE_CATEGORIA = value;
					this.SendPropertyChanged("NOMBRE_CATEGORIA");
					this.OnNOMBRE_CATEGORIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO_CATEGORIA", DbType="Char(1) NOT NULL")]
		public char ESTADO_CATEGORIA
		{
			get
			{
				return this._ESTADO_CATEGORIA;
			}
			set
			{
				if ((this._ESTADO_CATEGORIA != value))
				{
					this.OnESTADO_CATEGORIAChanging(value);
					this.SendPropertyChanging();
					this._ESTADO_CATEGORIA = value;
					this.SendPropertyChanged("ESTADO_CATEGORIA");
					this.OnESTADO_CATEGORIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLCATEGORIA_TBLPRODUCTOS", Storage="_TBLPRODUCTOS", ThisKey="ID_CATEGORIA", OtherKey="TBLCATEGORIA_ID")]
		public EntitySet<TBLPRODUCTOS> TBLPRODUCTOS
		{
			get
			{
				return this._TBLPRODUCTOS;
			}
			set
			{
				this._TBLPRODUCTOS.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBLPRODUCTOS(TBLPRODUCTOS entity)
		{
			this.SendPropertyChanging();
			entity.TBLCATEGORIA = this;
		}
		
		private void detach_TBLPRODUCTOS(TBLPRODUCTOS entity)
		{
			this.SendPropertyChanging();
			entity.TBLCATEGORIA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBLCESTA")]
	public partial class TBLCESTA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_CESTA;
		
		private int _CANTIDAD_CESTA;
		
		private double _PRECIO_CESTA;
		
		private EntitySet<TBLCLIENTE_TBLCESTA> _TBLCLIENTE_TBLCESTA;
		
		private EntitySet<TBLPRODUCTOS_TBLCESTA> _TBLPRODUCTOS_TBLCESTA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CESTAChanging(int value);
    partial void OnID_CESTAChanged();
    partial void OnCANTIDAD_CESTAChanging(int value);
    partial void OnCANTIDAD_CESTAChanged();
    partial void OnPRECIO_CESTAChanging(double value);
    partial void OnPRECIO_CESTAChanged();
    #endregion
		
		public TBLCESTA()
		{
			this._TBLCLIENTE_TBLCESTA = new EntitySet<TBLCLIENTE_TBLCESTA>(new Action<TBLCLIENTE_TBLCESTA>(this.attach_TBLCLIENTE_TBLCESTA), new Action<TBLCLIENTE_TBLCESTA>(this.detach_TBLCLIENTE_TBLCESTA));
			this._TBLPRODUCTOS_TBLCESTA = new EntitySet<TBLPRODUCTOS_TBLCESTA>(new Action<TBLPRODUCTOS_TBLCESTA>(this.attach_TBLPRODUCTOS_TBLCESTA), new Action<TBLPRODUCTOS_TBLCESTA>(this.detach_TBLPRODUCTOS_TBLCESTA));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CESTA", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_CESTA
		{
			get
			{
				return this._ID_CESTA;
			}
			set
			{
				if ((this._ID_CESTA != value))
				{
					this.OnID_CESTAChanging(value);
					this.SendPropertyChanging();
					this._ID_CESTA = value;
					this.SendPropertyChanged("ID_CESTA");
					this.OnID_CESTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CANTIDAD_CESTA", DbType="Int NOT NULL")]
		public int CANTIDAD_CESTA
		{
			get
			{
				return this._CANTIDAD_CESTA;
			}
			set
			{
				if ((this._CANTIDAD_CESTA != value))
				{
					this.OnCANTIDAD_CESTAChanging(value);
					this.SendPropertyChanging();
					this._CANTIDAD_CESTA = value;
					this.SendPropertyChanged("CANTIDAD_CESTA");
					this.OnCANTIDAD_CESTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRECIO_CESTA", DbType="Float NOT NULL")]
		public double PRECIO_CESTA
		{
			get
			{
				return this._PRECIO_CESTA;
			}
			set
			{
				if ((this._PRECIO_CESTA != value))
				{
					this.OnPRECIO_CESTAChanging(value);
					this.SendPropertyChanging();
					this._PRECIO_CESTA = value;
					this.SendPropertyChanged("PRECIO_CESTA");
					this.OnPRECIO_CESTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLCESTA_TBLCLIENTE_TBLCESTA", Storage="_TBLCLIENTE_TBLCESTA", ThisKey="ID_CESTA", OtherKey="TBLCESTA_ID")]
		public EntitySet<TBLCLIENTE_TBLCESTA> TBLCLIENTE_TBLCESTA
		{
			get
			{
				return this._TBLCLIENTE_TBLCESTA;
			}
			set
			{
				this._TBLCLIENTE_TBLCESTA.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLCESTA_TBLPRODUCTOS_TBLCESTA", Storage="_TBLPRODUCTOS_TBLCESTA", ThisKey="ID_CESTA", OtherKey="TBLCESTA_ID")]
		public EntitySet<TBLPRODUCTOS_TBLCESTA> TBLPRODUCTOS_TBLCESTA
		{
			get
			{
				return this._TBLPRODUCTOS_TBLCESTA;
			}
			set
			{
				this._TBLPRODUCTOS_TBLCESTA.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBLCLIENTE_TBLCESTA(TBLCLIENTE_TBLCESTA entity)
		{
			this.SendPropertyChanging();
			entity.TBLCESTA = this;
		}
		
		private void detach_TBLCLIENTE_TBLCESTA(TBLCLIENTE_TBLCESTA entity)
		{
			this.SendPropertyChanging();
			entity.TBLCESTA = null;
		}
		
		private void attach_TBLPRODUCTOS_TBLCESTA(TBLPRODUCTOS_TBLCESTA entity)
		{
			this.SendPropertyChanging();
			entity.TBLCESTA = this;
		}
		
		private void detach_TBLPRODUCTOS_TBLCESTA(TBLPRODUCTOS_TBLCESTA entity)
		{
			this.SendPropertyChanging();
			entity.TBLCESTA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBLCLIENTE")]
	public partial class TBLCLIENTE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_CLIENTE;
		
		private int _TBLUSUARIOS_ID;
		
		private char _ESTADO_CLIENTE;
		
		private EntitySet<TBLCLIENTE_TBLCESTA> _TBLCLIENTE_TBLCESTA;
		
		private EntitySet<TBLCOMPRA> _TBLCOMPRA;
		
		private EntitySet<TBLDIRECCIONES> _TBLDIRECCIONES;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CLIENTEChanging(int value);
    partial void OnID_CLIENTEChanged();
    partial void OnTBLUSUARIOS_IDChanging(int value);
    partial void OnTBLUSUARIOS_IDChanged();
    partial void OnESTADO_CLIENTEChanging(char value);
    partial void OnESTADO_CLIENTEChanged();
    #endregion
		
		public TBLCLIENTE()
		{
			this._TBLCLIENTE_TBLCESTA = new EntitySet<TBLCLIENTE_TBLCESTA>(new Action<TBLCLIENTE_TBLCESTA>(this.attach_TBLCLIENTE_TBLCESTA), new Action<TBLCLIENTE_TBLCESTA>(this.detach_TBLCLIENTE_TBLCESTA));
			this._TBLCOMPRA = new EntitySet<TBLCOMPRA>(new Action<TBLCOMPRA>(this.attach_TBLCOMPRA), new Action<TBLCOMPRA>(this.detach_TBLCOMPRA));
			this._TBLDIRECCIONES = new EntitySet<TBLDIRECCIONES>(new Action<TBLDIRECCIONES>(this.attach_TBLDIRECCIONES), new Action<TBLDIRECCIONES>(this.detach_TBLDIRECCIONES));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CLIENTE", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_CLIENTE
		{
			get
			{
				return this._ID_CLIENTE;
			}
			set
			{
				if ((this._ID_CLIENTE != value))
				{
					this.OnID_CLIENTEChanging(value);
					this.SendPropertyChanging();
					this._ID_CLIENTE = value;
					this.SendPropertyChanged("ID_CLIENTE");
					this.OnID_CLIENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TBLUSUARIOS_ID", DbType="Int NOT NULL")]
		public int TBLUSUARIOS_ID
		{
			get
			{
				return this._TBLUSUARIOS_ID;
			}
			set
			{
				if ((this._TBLUSUARIOS_ID != value))
				{
					this.OnTBLUSUARIOS_IDChanging(value);
					this.SendPropertyChanging();
					this._TBLUSUARIOS_ID = value;
					this.SendPropertyChanged("TBLUSUARIOS_ID");
					this.OnTBLUSUARIOS_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO_CLIENTE", DbType="Char(1) NOT NULL")]
		public char ESTADO_CLIENTE
		{
			get
			{
				return this._ESTADO_CLIENTE;
			}
			set
			{
				if ((this._ESTADO_CLIENTE != value))
				{
					this.OnESTADO_CLIENTEChanging(value);
					this.SendPropertyChanging();
					this._ESTADO_CLIENTE = value;
					this.SendPropertyChanged("ESTADO_CLIENTE");
					this.OnESTADO_CLIENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLCLIENTE_TBLCLIENTE_TBLCESTA", Storage="_TBLCLIENTE_TBLCESTA", ThisKey="ID_CLIENTE", OtherKey="TBLCLIENTE_ID")]
		public EntitySet<TBLCLIENTE_TBLCESTA> TBLCLIENTE_TBLCESTA
		{
			get
			{
				return this._TBLCLIENTE_TBLCESTA;
			}
			set
			{
				this._TBLCLIENTE_TBLCESTA.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLCLIENTE_TBLCOMPRA", Storage="_TBLCOMPRA", ThisKey="ID_CLIENTE", OtherKey="TBL_CLIENTE")]
		public EntitySet<TBLCOMPRA> TBLCOMPRA
		{
			get
			{
				return this._TBLCOMPRA;
			}
			set
			{
				this._TBLCOMPRA.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLCLIENTE_TBLDIRECCIONES", Storage="_TBLDIRECCIONES", ThisKey="ID_CLIENTE", OtherKey="TBLCLIENTE_ID")]
		public EntitySet<TBLDIRECCIONES> TBLDIRECCIONES
		{
			get
			{
				return this._TBLDIRECCIONES;
			}
			set
			{
				this._TBLDIRECCIONES.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBLCLIENTE_TBLCESTA(TBLCLIENTE_TBLCESTA entity)
		{
			this.SendPropertyChanging();
			entity.TBLCLIENTE = this;
		}
		
		private void detach_TBLCLIENTE_TBLCESTA(TBLCLIENTE_TBLCESTA entity)
		{
			this.SendPropertyChanging();
			entity.TBLCLIENTE = null;
		}
		
		private void attach_TBLCOMPRA(TBLCOMPRA entity)
		{
			this.SendPropertyChanging();
			entity.TBLCLIENTE = this;
		}
		
		private void detach_TBLCOMPRA(TBLCOMPRA entity)
		{
			this.SendPropertyChanging();
			entity.TBLCLIENTE = null;
		}
		
		private void attach_TBLDIRECCIONES(TBLDIRECCIONES entity)
		{
			this.SendPropertyChanging();
			entity.TBLCLIENTE = this;
		}
		
		private void detach_TBLDIRECCIONES(TBLDIRECCIONES entity)
		{
			this.SendPropertyChanging();
			entity.TBLCLIENTE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBLCLIENTE_TBLCESTA")]
	public partial class TBLCLIENTE_TBLCESTA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TBLCESTA_ID;
		
		private int _TBLCLIENTE_ID;
		
		private EntityRef<TBLCESTA> _TBLCESTA;
		
		private EntityRef<TBLCLIENTE> _TBLCLIENTE;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTBLCESTA_IDChanging(int value);
    partial void OnTBLCESTA_IDChanged();
    partial void OnTBLCLIENTE_IDChanging(int value);
    partial void OnTBLCLIENTE_IDChanged();
    #endregion
		
		public TBLCLIENTE_TBLCESTA()
		{
			this._TBLCESTA = default(EntityRef<TBLCESTA>);
			this._TBLCLIENTE = default(EntityRef<TBLCLIENTE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TBLCESTA_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TBLCESTA_ID
		{
			get
			{
				return this._TBLCESTA_ID;
			}
			set
			{
				if ((this._TBLCESTA_ID != value))
				{
					if (this._TBLCESTA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTBLCESTA_IDChanging(value);
					this.SendPropertyChanging();
					this._TBLCESTA_ID = value;
					this.SendPropertyChanged("TBLCESTA_ID");
					this.OnTBLCESTA_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TBLCLIENTE_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TBLCLIENTE_ID
		{
			get
			{
				return this._TBLCLIENTE_ID;
			}
			set
			{
				if ((this._TBLCLIENTE_ID != value))
				{
					if (this._TBLCLIENTE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTBLCLIENTE_IDChanging(value);
					this.SendPropertyChanging();
					this._TBLCLIENTE_ID = value;
					this.SendPropertyChanged("TBLCLIENTE_ID");
					this.OnTBLCLIENTE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLCESTA_TBLCLIENTE_TBLCESTA", Storage="_TBLCESTA", ThisKey="TBLCESTA_ID", OtherKey="ID_CESTA", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public TBLCESTA TBLCESTA
		{
			get
			{
				return this._TBLCESTA.Entity;
			}
			set
			{
				TBLCESTA previousValue = this._TBLCESTA.Entity;
				if (((previousValue != value) 
							|| (this._TBLCESTA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBLCESTA.Entity = null;
						previousValue.TBLCLIENTE_TBLCESTA.Remove(this);
					}
					this._TBLCESTA.Entity = value;
					if ((value != null))
					{
						value.TBLCLIENTE_TBLCESTA.Add(this);
						this._TBLCESTA_ID = value.ID_CESTA;
					}
					else
					{
						this._TBLCESTA_ID = default(int);
					}
					this.SendPropertyChanged("TBLCESTA");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLCLIENTE_TBLCLIENTE_TBLCESTA", Storage="_TBLCLIENTE", ThisKey="TBLCLIENTE_ID", OtherKey="ID_CLIENTE", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public TBLCLIENTE TBLCLIENTE
		{
			get
			{
				return this._TBLCLIENTE.Entity;
			}
			set
			{
				TBLCLIENTE previousValue = this._TBLCLIENTE.Entity;
				if (((previousValue != value) 
							|| (this._TBLCLIENTE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBLCLIENTE.Entity = null;
						previousValue.TBLCLIENTE_TBLCESTA.Remove(this);
					}
					this._TBLCLIENTE.Entity = value;
					if ((value != null))
					{
						value.TBLCLIENTE_TBLCESTA.Add(this);
						this._TBLCLIENTE_ID = value.ID_CLIENTE;
					}
					else
					{
						this._TBLCLIENTE_ID = default(int);
					}
					this.SendPropertyChanged("TBLCLIENTE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBLCOMPRA")]
	public partial class TBLCOMPRA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_COMPRA;
		
		private int _TBL_CLIENTE;
		
		private System.DateTime _FECHA_COMPRA;
		
		private string _MEDIO_PAGO_COMPRA;
		
		private int _IVA_COMPRA;
		
		private float _SUBTOTAL_COMPRA;
		
		private float _TOTAL_COMPRA;
		
		private string _TIPO_ENVIO;
		
		private float _CARGO_ENVIO;
		
		private System.DateTime _FECHA_ENVIO;
		
		private char _ESTADO_COMPRA;
		
		private EntitySet<TBLCOMPRA_TBLITEMCOMPRA> _TBLCOMPRA_TBLITEMCOMPRA;
		
		private EntityRef<TBLCLIENTE> _TBLCLIENTE;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_COMPRAChanging(int value);
    partial void OnID_COMPRAChanged();
    partial void OnTBL_CLIENTEChanging(int value);
    partial void OnTBL_CLIENTEChanged();
    partial void OnFECHA_COMPRAChanging(System.DateTime value);
    partial void OnFECHA_COMPRAChanged();
    partial void OnMEDIO_PAGO_COMPRAChanging(string value);
    partial void OnMEDIO_PAGO_COMPRAChanged();
    partial void OnIVA_COMPRAChanging(int value);
    partial void OnIVA_COMPRAChanged();
    partial void OnSUBTOTAL_COMPRAChanging(float value);
    partial void OnSUBTOTAL_COMPRAChanged();
    partial void OnTOTAL_COMPRAChanging(float value);
    partial void OnTOTAL_COMPRAChanged();
    partial void OnTIPO_ENVIOChanging(string value);
    partial void OnTIPO_ENVIOChanged();
    partial void OnCARGO_ENVIOChanging(float value);
    partial void OnCARGO_ENVIOChanged();
    partial void OnFECHA_ENVIOChanging(System.DateTime value);
    partial void OnFECHA_ENVIOChanged();
    partial void OnESTADO_COMPRAChanging(char value);
    partial void OnESTADO_COMPRAChanged();
    #endregion
		
		public TBLCOMPRA()
		{
			this._TBLCOMPRA_TBLITEMCOMPRA = new EntitySet<TBLCOMPRA_TBLITEMCOMPRA>(new Action<TBLCOMPRA_TBLITEMCOMPRA>(this.attach_TBLCOMPRA_TBLITEMCOMPRA), new Action<TBLCOMPRA_TBLITEMCOMPRA>(this.detach_TBLCOMPRA_TBLITEMCOMPRA));
			this._TBLCLIENTE = default(EntityRef<TBLCLIENTE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_COMPRA", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_COMPRA
		{
			get
			{
				return this._ID_COMPRA;
			}
			set
			{
				if ((this._ID_COMPRA != value))
				{
					this.OnID_COMPRAChanging(value);
					this.SendPropertyChanging();
					this._ID_COMPRA = value;
					this.SendPropertyChanged("ID_COMPRA");
					this.OnID_COMPRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TBL_CLIENTE", DbType="Int NOT NULL")]
		public int TBL_CLIENTE
		{
			get
			{
				return this._TBL_CLIENTE;
			}
			set
			{
				if ((this._TBL_CLIENTE != value))
				{
					if (this._TBLCLIENTE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTBL_CLIENTEChanging(value);
					this.SendPropertyChanging();
					this._TBL_CLIENTE = value;
					this.SendPropertyChanged("TBL_CLIENTE");
					this.OnTBL_CLIENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_COMPRA", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_COMPRA
		{
			get
			{
				return this._FECHA_COMPRA;
			}
			set
			{
				if ((this._FECHA_COMPRA != value))
				{
					this.OnFECHA_COMPRAChanging(value);
					this.SendPropertyChanging();
					this._FECHA_COMPRA = value;
					this.SendPropertyChanged("FECHA_COMPRA");
					this.OnFECHA_COMPRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MEDIO_PAGO_COMPRA", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MEDIO_PAGO_COMPRA
		{
			get
			{
				return this._MEDIO_PAGO_COMPRA;
			}
			set
			{
				if ((this._MEDIO_PAGO_COMPRA != value))
				{
					this.OnMEDIO_PAGO_COMPRAChanging(value);
					this.SendPropertyChanging();
					this._MEDIO_PAGO_COMPRA = value;
					this.SendPropertyChanged("MEDIO_PAGO_COMPRA");
					this.OnMEDIO_PAGO_COMPRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IVA_COMPRA", DbType="Int NOT NULL")]
		public int IVA_COMPRA
		{
			get
			{
				return this._IVA_COMPRA;
			}
			set
			{
				if ((this._IVA_COMPRA != value))
				{
					this.OnIVA_COMPRAChanging(value);
					this.SendPropertyChanging();
					this._IVA_COMPRA = value;
					this.SendPropertyChanged("IVA_COMPRA");
					this.OnIVA_COMPRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBTOTAL_COMPRA", DbType="Real NOT NULL")]
		public float SUBTOTAL_COMPRA
		{
			get
			{
				return this._SUBTOTAL_COMPRA;
			}
			set
			{
				if ((this._SUBTOTAL_COMPRA != value))
				{
					this.OnSUBTOTAL_COMPRAChanging(value);
					this.SendPropertyChanging();
					this._SUBTOTAL_COMPRA = value;
					this.SendPropertyChanged("SUBTOTAL_COMPRA");
					this.OnSUBTOTAL_COMPRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_COMPRA", DbType="Real NOT NULL")]
		public float TOTAL_COMPRA
		{
			get
			{
				return this._TOTAL_COMPRA;
			}
			set
			{
				if ((this._TOTAL_COMPRA != value))
				{
					this.OnTOTAL_COMPRAChanging(value);
					this.SendPropertyChanging();
					this._TOTAL_COMPRA = value;
					this.SendPropertyChanged("TOTAL_COMPRA");
					this.OnTOTAL_COMPRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO_ENVIO", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TIPO_ENVIO
		{
			get
			{
				return this._TIPO_ENVIO;
			}
			set
			{
				if ((this._TIPO_ENVIO != value))
				{
					this.OnTIPO_ENVIOChanging(value);
					this.SendPropertyChanging();
					this._TIPO_ENVIO = value;
					this.SendPropertyChanged("TIPO_ENVIO");
					this.OnTIPO_ENVIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARGO_ENVIO", DbType="Real NOT NULL")]
		public float CARGO_ENVIO
		{
			get
			{
				return this._CARGO_ENVIO;
			}
			set
			{
				if ((this._CARGO_ENVIO != value))
				{
					this.OnCARGO_ENVIOChanging(value);
					this.SendPropertyChanging();
					this._CARGO_ENVIO = value;
					this.SendPropertyChanged("CARGO_ENVIO");
					this.OnCARGO_ENVIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_ENVIO", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_ENVIO
		{
			get
			{
				return this._FECHA_ENVIO;
			}
			set
			{
				if ((this._FECHA_ENVIO != value))
				{
					this.OnFECHA_ENVIOChanging(value);
					this.SendPropertyChanging();
					this._FECHA_ENVIO = value;
					this.SendPropertyChanged("FECHA_ENVIO");
					this.OnFECHA_ENVIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO_COMPRA", DbType="Char(1) NOT NULL")]
		public char ESTADO_COMPRA
		{
			get
			{
				return this._ESTADO_COMPRA;
			}
			set
			{
				if ((this._ESTADO_COMPRA != value))
				{
					this.OnESTADO_COMPRAChanging(value);
					this.SendPropertyChanging();
					this._ESTADO_COMPRA = value;
					this.SendPropertyChanged("ESTADO_COMPRA");
					this.OnESTADO_COMPRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLCOMPRA_TBLCOMPRA_TBLITEMCOMPRA", Storage="_TBLCOMPRA_TBLITEMCOMPRA", ThisKey="ID_COMPRA", OtherKey="TBLCOMPRA_ID")]
		public EntitySet<TBLCOMPRA_TBLITEMCOMPRA> TBLCOMPRA_TBLITEMCOMPRA
		{
			get
			{
				return this._TBLCOMPRA_TBLITEMCOMPRA;
			}
			set
			{
				this._TBLCOMPRA_TBLITEMCOMPRA.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLCLIENTE_TBLCOMPRA", Storage="_TBLCLIENTE", ThisKey="TBL_CLIENTE", OtherKey="ID_CLIENTE", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public TBLCLIENTE TBLCLIENTE
		{
			get
			{
				return this._TBLCLIENTE.Entity;
			}
			set
			{
				TBLCLIENTE previousValue = this._TBLCLIENTE.Entity;
				if (((previousValue != value) 
							|| (this._TBLCLIENTE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBLCLIENTE.Entity = null;
						previousValue.TBLCOMPRA.Remove(this);
					}
					this._TBLCLIENTE.Entity = value;
					if ((value != null))
					{
						value.TBLCOMPRA.Add(this);
						this._TBL_CLIENTE = value.ID_CLIENTE;
					}
					else
					{
						this._TBL_CLIENTE = default(int);
					}
					this.SendPropertyChanged("TBLCLIENTE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBLCOMPRA_TBLITEMCOMPRA(TBLCOMPRA_TBLITEMCOMPRA entity)
		{
			this.SendPropertyChanging();
			entity.TBLCOMPRA = this;
		}
		
		private void detach_TBLCOMPRA_TBLITEMCOMPRA(TBLCOMPRA_TBLITEMCOMPRA entity)
		{
			this.SendPropertyChanging();
			entity.TBLCOMPRA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBLCOMPRA_TBLITEMCOMPRA")]
	public partial class TBLCOMPRA_TBLITEMCOMPRA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TBLITEMCOMPRA_ID;
		
		private int _TBLCOMPRA_ID;
		
		private EntityRef<TBLCOMPRA> _TBLCOMPRA;
		
		private EntityRef<TBLITEMCOMPRA> _TBLITEMCOMPRA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTBLITEMCOMPRA_IDChanging(int value);
    partial void OnTBLITEMCOMPRA_IDChanged();
    partial void OnTBLCOMPRA_IDChanging(int value);
    partial void OnTBLCOMPRA_IDChanged();
    #endregion
		
		public TBLCOMPRA_TBLITEMCOMPRA()
		{
			this._TBLCOMPRA = default(EntityRef<TBLCOMPRA>);
			this._TBLITEMCOMPRA = default(EntityRef<TBLITEMCOMPRA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TBLITEMCOMPRA_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TBLITEMCOMPRA_ID
		{
			get
			{
				return this._TBLITEMCOMPRA_ID;
			}
			set
			{
				if ((this._TBLITEMCOMPRA_ID != value))
				{
					if (this._TBLITEMCOMPRA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTBLITEMCOMPRA_IDChanging(value);
					this.SendPropertyChanging();
					this._TBLITEMCOMPRA_ID = value;
					this.SendPropertyChanged("TBLITEMCOMPRA_ID");
					this.OnTBLITEMCOMPRA_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TBLCOMPRA_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TBLCOMPRA_ID
		{
			get
			{
				return this._TBLCOMPRA_ID;
			}
			set
			{
				if ((this._TBLCOMPRA_ID != value))
				{
					if (this._TBLCOMPRA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTBLCOMPRA_IDChanging(value);
					this.SendPropertyChanging();
					this._TBLCOMPRA_ID = value;
					this.SendPropertyChanged("TBLCOMPRA_ID");
					this.OnTBLCOMPRA_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLCOMPRA_TBLCOMPRA_TBLITEMCOMPRA", Storage="_TBLCOMPRA", ThisKey="TBLCOMPRA_ID", OtherKey="ID_COMPRA", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public TBLCOMPRA TBLCOMPRA
		{
			get
			{
				return this._TBLCOMPRA.Entity;
			}
			set
			{
				TBLCOMPRA previousValue = this._TBLCOMPRA.Entity;
				if (((previousValue != value) 
							|| (this._TBLCOMPRA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBLCOMPRA.Entity = null;
						previousValue.TBLCOMPRA_TBLITEMCOMPRA.Remove(this);
					}
					this._TBLCOMPRA.Entity = value;
					if ((value != null))
					{
						value.TBLCOMPRA_TBLITEMCOMPRA.Add(this);
						this._TBLCOMPRA_ID = value.ID_COMPRA;
					}
					else
					{
						this._TBLCOMPRA_ID = default(int);
					}
					this.SendPropertyChanged("TBLCOMPRA");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLITEMCOMPRA_TBLCOMPRA_TBLITEMCOMPRA", Storage="_TBLITEMCOMPRA", ThisKey="TBLITEMCOMPRA_ID", OtherKey="ID_ITEMCOMPRA", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public TBLITEMCOMPRA TBLITEMCOMPRA
		{
			get
			{
				return this._TBLITEMCOMPRA.Entity;
			}
			set
			{
				TBLITEMCOMPRA previousValue = this._TBLITEMCOMPRA.Entity;
				if (((previousValue != value) 
							|| (this._TBLITEMCOMPRA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBLITEMCOMPRA.Entity = null;
						previousValue.TBLCOMPRA_TBLITEMCOMPRA.Remove(this);
					}
					this._TBLITEMCOMPRA.Entity = value;
					if ((value != null))
					{
						value.TBLCOMPRA_TBLITEMCOMPRA.Add(this);
						this._TBLITEMCOMPRA_ID = value.ID_ITEMCOMPRA;
					}
					else
					{
						this._TBLITEMCOMPRA_ID = default(int);
					}
					this.SendPropertyChanged("TBLITEMCOMPRA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBLDIRECCIONES")]
	public partial class TBLDIRECCIONES : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_DIRECCIONES;
		
		private System.Nullable<int> _TBLCLIENTE_ID;
		
		private string _DESC_DIRECCION;
		
		private string _PROV_DIRECCION;
		
		private string _COD_POST_DIRECCION;
		
		private string _ESTADO_DIRECCION;
		
		private EntityRef<TBLCLIENTE> _TBLCLIENTE;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_DIRECCIONESChanging(int value);
    partial void OnID_DIRECCIONESChanged();
    partial void OnTBLCLIENTE_IDChanging(System.Nullable<int> value);
    partial void OnTBLCLIENTE_IDChanged();
    partial void OnDESC_DIRECCIONChanging(string value);
    partial void OnDESC_DIRECCIONChanged();
    partial void OnPROV_DIRECCIONChanging(string value);
    partial void OnPROV_DIRECCIONChanged();
    partial void OnCOD_POST_DIRECCIONChanging(string value);
    partial void OnCOD_POST_DIRECCIONChanged();
    partial void OnESTADO_DIRECCIONChanging(string value);
    partial void OnESTADO_DIRECCIONChanged();
    #endregion
		
		public TBLDIRECCIONES()
		{
			this._TBLCLIENTE = default(EntityRef<TBLCLIENTE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DIRECCIONES", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_DIRECCIONES
		{
			get
			{
				return this._ID_DIRECCIONES;
			}
			set
			{
				if ((this._ID_DIRECCIONES != value))
				{
					this.OnID_DIRECCIONESChanging(value);
					this.SendPropertyChanging();
					this._ID_DIRECCIONES = value;
					this.SendPropertyChanged("ID_DIRECCIONES");
					this.OnID_DIRECCIONESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TBLCLIENTE_ID", DbType="Int")]
		public System.Nullable<int> TBLCLIENTE_ID
		{
			get
			{
				return this._TBLCLIENTE_ID;
			}
			set
			{
				if ((this._TBLCLIENTE_ID != value))
				{
					if (this._TBLCLIENTE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTBLCLIENTE_IDChanging(value);
					this.SendPropertyChanging();
					this._TBLCLIENTE_ID = value;
					this.SendPropertyChanged("TBLCLIENTE_ID");
					this.OnTBLCLIENTE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESC_DIRECCION", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string DESC_DIRECCION
		{
			get
			{
				return this._DESC_DIRECCION;
			}
			set
			{
				if ((this._DESC_DIRECCION != value))
				{
					this.OnDESC_DIRECCIONChanging(value);
					this.SendPropertyChanging();
					this._DESC_DIRECCION = value;
					this.SendPropertyChanged("DESC_DIRECCION");
					this.OnDESC_DIRECCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROV_DIRECCION", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string PROV_DIRECCION
		{
			get
			{
				return this._PROV_DIRECCION;
			}
			set
			{
				if ((this._PROV_DIRECCION != value))
				{
					this.OnPROV_DIRECCIONChanging(value);
					this.SendPropertyChanging();
					this._PROV_DIRECCION = value;
					this.SendPropertyChanged("PROV_DIRECCION");
					this.OnPROV_DIRECCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COD_POST_DIRECCION", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string COD_POST_DIRECCION
		{
			get
			{
				return this._COD_POST_DIRECCION;
			}
			set
			{
				if ((this._COD_POST_DIRECCION != value))
				{
					this.OnCOD_POST_DIRECCIONChanging(value);
					this.SendPropertyChanging();
					this._COD_POST_DIRECCION = value;
					this.SendPropertyChanged("COD_POST_DIRECCION");
					this.OnCOD_POST_DIRECCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO_DIRECCION", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string ESTADO_DIRECCION
		{
			get
			{
				return this._ESTADO_DIRECCION;
			}
			set
			{
				if ((this._ESTADO_DIRECCION != value))
				{
					this.OnESTADO_DIRECCIONChanging(value);
					this.SendPropertyChanging();
					this._ESTADO_DIRECCION = value;
					this.SendPropertyChanged("ESTADO_DIRECCION");
					this.OnESTADO_DIRECCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLCLIENTE_TBLDIRECCIONES", Storage="_TBLCLIENTE", ThisKey="TBLCLIENTE_ID", OtherKey="ID_CLIENTE", IsForeignKey=true, DeleteRule="CASCADE")]
		public TBLCLIENTE TBLCLIENTE
		{
			get
			{
				return this._TBLCLIENTE.Entity;
			}
			set
			{
				TBLCLIENTE previousValue = this._TBLCLIENTE.Entity;
				if (((previousValue != value) 
							|| (this._TBLCLIENTE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBLCLIENTE.Entity = null;
						previousValue.TBLDIRECCIONES.Remove(this);
					}
					this._TBLCLIENTE.Entity = value;
					if ((value != null))
					{
						value.TBLDIRECCIONES.Add(this);
						this._TBLCLIENTE_ID = value.ID_CLIENTE;
					}
					else
					{
						this._TBLCLIENTE_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("TBLCLIENTE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBLIMPUESTOS")]
	public partial class TBLIMPUESTOS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_IMPUESTO;
		
		private string _PAIS_IMPUESTO;
		
		private int _IVA_IMPUESTO;
		
		private EntitySet<TBLPRODUCTOS> _TBLPRODUCTOS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_IMPUESTOChanging(int value);
    partial void OnID_IMPUESTOChanged();
    partial void OnPAIS_IMPUESTOChanging(string value);
    partial void OnPAIS_IMPUESTOChanged();
    partial void OnIVA_IMPUESTOChanging(int value);
    partial void OnIVA_IMPUESTOChanged();
    #endregion
		
		public TBLIMPUESTOS()
		{
			this._TBLPRODUCTOS = new EntitySet<TBLPRODUCTOS>(new Action<TBLPRODUCTOS>(this.attach_TBLPRODUCTOS), new Action<TBLPRODUCTOS>(this.detach_TBLPRODUCTOS));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_IMPUESTO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_IMPUESTO
		{
			get
			{
				return this._ID_IMPUESTO;
			}
			set
			{
				if ((this._ID_IMPUESTO != value))
				{
					this.OnID_IMPUESTOChanging(value);
					this.SendPropertyChanging();
					this._ID_IMPUESTO = value;
					this.SendPropertyChanged("ID_IMPUESTO");
					this.OnID_IMPUESTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAIS_IMPUESTO", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string PAIS_IMPUESTO
		{
			get
			{
				return this._PAIS_IMPUESTO;
			}
			set
			{
				if ((this._PAIS_IMPUESTO != value))
				{
					this.OnPAIS_IMPUESTOChanging(value);
					this.SendPropertyChanging();
					this._PAIS_IMPUESTO = value;
					this.SendPropertyChanged("PAIS_IMPUESTO");
					this.OnPAIS_IMPUESTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IVA_IMPUESTO", DbType="Int NOT NULL")]
		public int IVA_IMPUESTO
		{
			get
			{
				return this._IVA_IMPUESTO;
			}
			set
			{
				if ((this._IVA_IMPUESTO != value))
				{
					this.OnIVA_IMPUESTOChanging(value);
					this.SendPropertyChanging();
					this._IVA_IMPUESTO = value;
					this.SendPropertyChanged("IVA_IMPUESTO");
					this.OnIVA_IMPUESTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLIMPUESTOS_TBLPRODUCTOS", Storage="_TBLPRODUCTOS", ThisKey="ID_IMPUESTO", OtherKey="TBLIMPUESTOS_ID")]
		public EntitySet<TBLPRODUCTOS> TBLPRODUCTOS
		{
			get
			{
				return this._TBLPRODUCTOS;
			}
			set
			{
				this._TBLPRODUCTOS.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBLPRODUCTOS(TBLPRODUCTOS entity)
		{
			this.SendPropertyChanging();
			entity.TBLIMPUESTOS = this;
		}
		
		private void detach_TBLPRODUCTOS(TBLPRODUCTOS entity)
		{
			this.SendPropertyChanging();
			entity.TBLIMPUESTOS = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBLITEMCOMPRA")]
	public partial class TBLITEMCOMPRA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_ITEMCOMPRA;
		
		private System.Nullable<int> _TBLPRODUCTO_ID;
		
		private float _PRECIO_SUBTOTAL_ITEMCOMPRA;
		
		private int _CANTIDAD_ITEMCOMPRA;
		
		private EntitySet<TBLCOMPRA_TBLITEMCOMPRA> _TBLCOMPRA_TBLITEMCOMPRA;
		
		private EntityRef<TBLPRODUCTOS> _TBLPRODUCTOS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ITEMCOMPRAChanging(int value);
    partial void OnID_ITEMCOMPRAChanged();
    partial void OnTBLPRODUCTO_IDChanging(System.Nullable<int> value);
    partial void OnTBLPRODUCTO_IDChanged();
    partial void OnPRECIO_SUBTOTAL_ITEMCOMPRAChanging(float value);
    partial void OnPRECIO_SUBTOTAL_ITEMCOMPRAChanged();
    partial void OnCANTIDAD_ITEMCOMPRAChanging(int value);
    partial void OnCANTIDAD_ITEMCOMPRAChanged();
    #endregion
		
		public TBLITEMCOMPRA()
		{
			this._TBLCOMPRA_TBLITEMCOMPRA = new EntitySet<TBLCOMPRA_TBLITEMCOMPRA>(new Action<TBLCOMPRA_TBLITEMCOMPRA>(this.attach_TBLCOMPRA_TBLITEMCOMPRA), new Action<TBLCOMPRA_TBLITEMCOMPRA>(this.detach_TBLCOMPRA_TBLITEMCOMPRA));
			this._TBLPRODUCTOS = default(EntityRef<TBLPRODUCTOS>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ITEMCOMPRA", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_ITEMCOMPRA
		{
			get
			{
				return this._ID_ITEMCOMPRA;
			}
			set
			{
				if ((this._ID_ITEMCOMPRA != value))
				{
					this.OnID_ITEMCOMPRAChanging(value);
					this.SendPropertyChanging();
					this._ID_ITEMCOMPRA = value;
					this.SendPropertyChanged("ID_ITEMCOMPRA");
					this.OnID_ITEMCOMPRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TBLPRODUCTO_ID", DbType="Int")]
		public System.Nullable<int> TBLPRODUCTO_ID
		{
			get
			{
				return this._TBLPRODUCTO_ID;
			}
			set
			{
				if ((this._TBLPRODUCTO_ID != value))
				{
					if (this._TBLPRODUCTOS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTBLPRODUCTO_IDChanging(value);
					this.SendPropertyChanging();
					this._TBLPRODUCTO_ID = value;
					this.SendPropertyChanged("TBLPRODUCTO_ID");
					this.OnTBLPRODUCTO_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRECIO_SUBTOTAL_ITEMCOMPRA", DbType="Real NOT NULL")]
		public float PRECIO_SUBTOTAL_ITEMCOMPRA
		{
			get
			{
				return this._PRECIO_SUBTOTAL_ITEMCOMPRA;
			}
			set
			{
				if ((this._PRECIO_SUBTOTAL_ITEMCOMPRA != value))
				{
					this.OnPRECIO_SUBTOTAL_ITEMCOMPRAChanging(value);
					this.SendPropertyChanging();
					this._PRECIO_SUBTOTAL_ITEMCOMPRA = value;
					this.SendPropertyChanged("PRECIO_SUBTOTAL_ITEMCOMPRA");
					this.OnPRECIO_SUBTOTAL_ITEMCOMPRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CANTIDAD_ITEMCOMPRA", DbType="Int NOT NULL")]
		public int CANTIDAD_ITEMCOMPRA
		{
			get
			{
				return this._CANTIDAD_ITEMCOMPRA;
			}
			set
			{
				if ((this._CANTIDAD_ITEMCOMPRA != value))
				{
					this.OnCANTIDAD_ITEMCOMPRAChanging(value);
					this.SendPropertyChanging();
					this._CANTIDAD_ITEMCOMPRA = value;
					this.SendPropertyChanged("CANTIDAD_ITEMCOMPRA");
					this.OnCANTIDAD_ITEMCOMPRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLITEMCOMPRA_TBLCOMPRA_TBLITEMCOMPRA", Storage="_TBLCOMPRA_TBLITEMCOMPRA", ThisKey="ID_ITEMCOMPRA", OtherKey="TBLITEMCOMPRA_ID")]
		public EntitySet<TBLCOMPRA_TBLITEMCOMPRA> TBLCOMPRA_TBLITEMCOMPRA
		{
			get
			{
				return this._TBLCOMPRA_TBLITEMCOMPRA;
			}
			set
			{
				this._TBLCOMPRA_TBLITEMCOMPRA.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLPRODUCTOS_TBLITEMCOMPRA", Storage="_TBLPRODUCTOS", ThisKey="TBLPRODUCTO_ID", OtherKey="ID_PRODUCTO", IsForeignKey=true, DeleteRule="CASCADE")]
		public TBLPRODUCTOS TBLPRODUCTOS
		{
			get
			{
				return this._TBLPRODUCTOS.Entity;
			}
			set
			{
				TBLPRODUCTOS previousValue = this._TBLPRODUCTOS.Entity;
				if (((previousValue != value) 
							|| (this._TBLPRODUCTOS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBLPRODUCTOS.Entity = null;
						previousValue.TBLITEMCOMPRA.Remove(this);
					}
					this._TBLPRODUCTOS.Entity = value;
					if ((value != null))
					{
						value.TBLITEMCOMPRA.Add(this);
						this._TBLPRODUCTO_ID = value.ID_PRODUCTO;
					}
					else
					{
						this._TBLPRODUCTO_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("TBLPRODUCTOS");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBLCOMPRA_TBLITEMCOMPRA(TBLCOMPRA_TBLITEMCOMPRA entity)
		{
			this.SendPropertyChanging();
			entity.TBLITEMCOMPRA = this;
		}
		
		private void detach_TBLCOMPRA_TBLITEMCOMPRA(TBLCOMPRA_TBLITEMCOMPRA entity)
		{
			this.SendPropertyChanging();
			entity.TBLITEMCOMPRA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBLMETODOPAGO")]
	public partial class TBLMETODOPAGO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_METODO_PAGO;
		
		private string _DESC_METODO_PAGO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_METODO_PAGOChanging(int value);
    partial void OnID_METODO_PAGOChanged();
    partial void OnDESC_METODO_PAGOChanging(string value);
    partial void OnDESC_METODO_PAGOChanged();
    #endregion
		
		public TBLMETODOPAGO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_METODO_PAGO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_METODO_PAGO
		{
			get
			{
				return this._ID_METODO_PAGO;
			}
			set
			{
				if ((this._ID_METODO_PAGO != value))
				{
					this.OnID_METODO_PAGOChanging(value);
					this.SendPropertyChanging();
					this._ID_METODO_PAGO = value;
					this.SendPropertyChanged("ID_METODO_PAGO");
					this.OnID_METODO_PAGOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESC_METODO_PAGO", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DESC_METODO_PAGO
		{
			get
			{
				return this._DESC_METODO_PAGO;
			}
			set
			{
				if ((this._DESC_METODO_PAGO != value))
				{
					this.OnDESC_METODO_PAGOChanging(value);
					this.SendPropertyChanging();
					this._DESC_METODO_PAGO = value;
					this.SendPropertyChanged("DESC_METODO_PAGO");
					this.OnDESC_METODO_PAGOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBLPRODUCTOS")]
	public partial class TBLPRODUCTOS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_PRODUCTO;
		
		private int _TBLIMPUESTOS_ID;
		
		private int _TBLCATEGORIA_ID;
		
		private string _NOM_PRODUCTO;
		
		private string _DESC_GRANDE_PRODUCTO;
		
		private string _DESC_PEQUE_PRODUCTO;
		
		private float _PRECIO_PRODUCTO;
		
		private int _STOCK_PRODUCTO;
		
		private string _IMAGEN_PRODUCTO;
		
		private System.DateTime _FECHA_PRODUCTO;
		
		private char _ESTADO_PRODUCTO;
		
		private EntitySet<TBLITEMCOMPRA> _TBLITEMCOMPRA;
		
		private EntitySet<TBLPRODUCTOS_TBLCESTA> _TBLPRODUCTOS_TBLCESTA;
		
		private EntityRef<TBLCATEGORIA> _TBLCATEGORIA;
		
		private EntityRef<TBLIMPUESTOS> _TBLIMPUESTOS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PRODUCTOChanging(int value);
    partial void OnID_PRODUCTOChanged();
    partial void OnTBLIMPUESTOS_IDChanging(int value);
    partial void OnTBLIMPUESTOS_IDChanged();
    partial void OnTBLCATEGORIA_IDChanging(int value);
    partial void OnTBLCATEGORIA_IDChanged();
    partial void OnNOM_PRODUCTOChanging(string value);
    partial void OnNOM_PRODUCTOChanged();
    partial void OnDESC_GRANDE_PRODUCTOChanging(string value);
    partial void OnDESC_GRANDE_PRODUCTOChanged();
    partial void OnDESC_PEQUE_PRODUCTOChanging(string value);
    partial void OnDESC_PEQUE_PRODUCTOChanged();
    partial void OnPRECIO_PRODUCTOChanging(float value);
    partial void OnPRECIO_PRODUCTOChanged();
    partial void OnSTOCK_PRODUCTOChanging(int value);
    partial void OnSTOCK_PRODUCTOChanged();
    partial void OnIMAGEN_PRODUCTOChanging(string value);
    partial void OnIMAGEN_PRODUCTOChanged();
    partial void OnFECHA_PRODUCTOChanging(System.DateTime value);
    partial void OnFECHA_PRODUCTOChanged();
    partial void OnESTADO_PRODUCTOChanging(char value);
    partial void OnESTADO_PRODUCTOChanged();
    #endregion
		
		public TBLPRODUCTOS()
		{
			this._TBLITEMCOMPRA = new EntitySet<TBLITEMCOMPRA>(new Action<TBLITEMCOMPRA>(this.attach_TBLITEMCOMPRA), new Action<TBLITEMCOMPRA>(this.detach_TBLITEMCOMPRA));
			this._TBLPRODUCTOS_TBLCESTA = new EntitySet<TBLPRODUCTOS_TBLCESTA>(new Action<TBLPRODUCTOS_TBLCESTA>(this.attach_TBLPRODUCTOS_TBLCESTA), new Action<TBLPRODUCTOS_TBLCESTA>(this.detach_TBLPRODUCTOS_TBLCESTA));
			this._TBLCATEGORIA = default(EntityRef<TBLCATEGORIA>);
			this._TBLIMPUESTOS = default(EntityRef<TBLIMPUESTOS>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRODUCTO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_PRODUCTO
		{
			get
			{
				return this._ID_PRODUCTO;
			}
			set
			{
				if ((this._ID_PRODUCTO != value))
				{
					this.OnID_PRODUCTOChanging(value);
					this.SendPropertyChanging();
					this._ID_PRODUCTO = value;
					this.SendPropertyChanged("ID_PRODUCTO");
					this.OnID_PRODUCTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TBLIMPUESTOS_ID", DbType="Int NOT NULL")]
		public int TBLIMPUESTOS_ID
		{
			get
			{
				return this._TBLIMPUESTOS_ID;
			}
			set
			{
				if ((this._TBLIMPUESTOS_ID != value))
				{
					if (this._TBLIMPUESTOS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTBLIMPUESTOS_IDChanging(value);
					this.SendPropertyChanging();
					this._TBLIMPUESTOS_ID = value;
					this.SendPropertyChanged("TBLIMPUESTOS_ID");
					this.OnTBLIMPUESTOS_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TBLCATEGORIA_ID", DbType="Int NOT NULL")]
		public int TBLCATEGORIA_ID
		{
			get
			{
				return this._TBLCATEGORIA_ID;
			}
			set
			{
				if ((this._TBLCATEGORIA_ID != value))
				{
					if (this._TBLCATEGORIA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTBLCATEGORIA_IDChanging(value);
					this.SendPropertyChanging();
					this._TBLCATEGORIA_ID = value;
					this.SendPropertyChanged("TBLCATEGORIA_ID");
					this.OnTBLCATEGORIA_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOM_PRODUCTO", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NOM_PRODUCTO
		{
			get
			{
				return this._NOM_PRODUCTO;
			}
			set
			{
				if ((this._NOM_PRODUCTO != value))
				{
					this.OnNOM_PRODUCTOChanging(value);
					this.SendPropertyChanging();
					this._NOM_PRODUCTO = value;
					this.SendPropertyChanged("NOM_PRODUCTO");
					this.OnNOM_PRODUCTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESC_GRANDE_PRODUCTO", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string DESC_GRANDE_PRODUCTO
		{
			get
			{
				return this._DESC_GRANDE_PRODUCTO;
			}
			set
			{
				if ((this._DESC_GRANDE_PRODUCTO != value))
				{
					this.OnDESC_GRANDE_PRODUCTOChanging(value);
					this.SendPropertyChanging();
					this._DESC_GRANDE_PRODUCTO = value;
					this.SendPropertyChanged("DESC_GRANDE_PRODUCTO");
					this.OnDESC_GRANDE_PRODUCTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESC_PEQUE_PRODUCTO", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string DESC_PEQUE_PRODUCTO
		{
			get
			{
				return this._DESC_PEQUE_PRODUCTO;
			}
			set
			{
				if ((this._DESC_PEQUE_PRODUCTO != value))
				{
					this.OnDESC_PEQUE_PRODUCTOChanging(value);
					this.SendPropertyChanging();
					this._DESC_PEQUE_PRODUCTO = value;
					this.SendPropertyChanged("DESC_PEQUE_PRODUCTO");
					this.OnDESC_PEQUE_PRODUCTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRECIO_PRODUCTO", DbType="Real NOT NULL")]
		public float PRECIO_PRODUCTO
		{
			get
			{
				return this._PRECIO_PRODUCTO;
			}
			set
			{
				if ((this._PRECIO_PRODUCTO != value))
				{
					this.OnPRECIO_PRODUCTOChanging(value);
					this.SendPropertyChanging();
					this._PRECIO_PRODUCTO = value;
					this.SendPropertyChanged("PRECIO_PRODUCTO");
					this.OnPRECIO_PRODUCTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOCK_PRODUCTO", DbType="Int NOT NULL")]
		public int STOCK_PRODUCTO
		{
			get
			{
				return this._STOCK_PRODUCTO;
			}
			set
			{
				if ((this._STOCK_PRODUCTO != value))
				{
					this.OnSTOCK_PRODUCTOChanging(value);
					this.SendPropertyChanging();
					this._STOCK_PRODUCTO = value;
					this.SendPropertyChanged("STOCK_PRODUCTO");
					this.OnSTOCK_PRODUCTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMAGEN_PRODUCTO", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string IMAGEN_PRODUCTO
		{
			get
			{
				return this._IMAGEN_PRODUCTO;
			}
			set
			{
				if ((this._IMAGEN_PRODUCTO != value))
				{
					this.OnIMAGEN_PRODUCTOChanging(value);
					this.SendPropertyChanging();
					this._IMAGEN_PRODUCTO = value;
					this.SendPropertyChanged("IMAGEN_PRODUCTO");
					this.OnIMAGEN_PRODUCTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_PRODUCTO", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_PRODUCTO
		{
			get
			{
				return this._FECHA_PRODUCTO;
			}
			set
			{
				if ((this._FECHA_PRODUCTO != value))
				{
					this.OnFECHA_PRODUCTOChanging(value);
					this.SendPropertyChanging();
					this._FECHA_PRODUCTO = value;
					this.SendPropertyChanged("FECHA_PRODUCTO");
					this.OnFECHA_PRODUCTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO_PRODUCTO", DbType="Char(1) NOT NULL")]
		public char ESTADO_PRODUCTO
		{
			get
			{
				return this._ESTADO_PRODUCTO;
			}
			set
			{
				if ((this._ESTADO_PRODUCTO != value))
				{
					this.OnESTADO_PRODUCTOChanging(value);
					this.SendPropertyChanging();
					this._ESTADO_PRODUCTO = value;
					this.SendPropertyChanged("ESTADO_PRODUCTO");
					this.OnESTADO_PRODUCTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLPRODUCTOS_TBLITEMCOMPRA", Storage="_TBLITEMCOMPRA", ThisKey="ID_PRODUCTO", OtherKey="TBLPRODUCTO_ID")]
		public EntitySet<TBLITEMCOMPRA> TBLITEMCOMPRA
		{
			get
			{
				return this._TBLITEMCOMPRA;
			}
			set
			{
				this._TBLITEMCOMPRA.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLPRODUCTOS_TBLPRODUCTOS_TBLCESTA", Storage="_TBLPRODUCTOS_TBLCESTA", ThisKey="ID_PRODUCTO", OtherKey="TBLPRODUCTO_ID")]
		public EntitySet<TBLPRODUCTOS_TBLCESTA> TBLPRODUCTOS_TBLCESTA
		{
			get
			{
				return this._TBLPRODUCTOS_TBLCESTA;
			}
			set
			{
				this._TBLPRODUCTOS_TBLCESTA.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLCATEGORIA_TBLPRODUCTOS", Storage="_TBLCATEGORIA", ThisKey="TBLCATEGORIA_ID", OtherKey="ID_CATEGORIA", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public TBLCATEGORIA TBLCATEGORIA
		{
			get
			{
				return this._TBLCATEGORIA.Entity;
			}
			set
			{
				TBLCATEGORIA previousValue = this._TBLCATEGORIA.Entity;
				if (((previousValue != value) 
							|| (this._TBLCATEGORIA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBLCATEGORIA.Entity = null;
						previousValue.TBLPRODUCTOS.Remove(this);
					}
					this._TBLCATEGORIA.Entity = value;
					if ((value != null))
					{
						value.TBLPRODUCTOS.Add(this);
						this._TBLCATEGORIA_ID = value.ID_CATEGORIA;
					}
					else
					{
						this._TBLCATEGORIA_ID = default(int);
					}
					this.SendPropertyChanged("TBLCATEGORIA");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLIMPUESTOS_TBLPRODUCTOS", Storage="_TBLIMPUESTOS", ThisKey="TBLIMPUESTOS_ID", OtherKey="ID_IMPUESTO", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public TBLIMPUESTOS TBLIMPUESTOS
		{
			get
			{
				return this._TBLIMPUESTOS.Entity;
			}
			set
			{
				TBLIMPUESTOS previousValue = this._TBLIMPUESTOS.Entity;
				if (((previousValue != value) 
							|| (this._TBLIMPUESTOS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBLIMPUESTOS.Entity = null;
						previousValue.TBLPRODUCTOS.Remove(this);
					}
					this._TBLIMPUESTOS.Entity = value;
					if ((value != null))
					{
						value.TBLPRODUCTOS.Add(this);
						this._TBLIMPUESTOS_ID = value.ID_IMPUESTO;
					}
					else
					{
						this._TBLIMPUESTOS_ID = default(int);
					}
					this.SendPropertyChanged("TBLIMPUESTOS");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBLITEMCOMPRA(TBLITEMCOMPRA entity)
		{
			this.SendPropertyChanging();
			entity.TBLPRODUCTOS = this;
		}
		
		private void detach_TBLITEMCOMPRA(TBLITEMCOMPRA entity)
		{
			this.SendPropertyChanging();
			entity.TBLPRODUCTOS = null;
		}
		
		private void attach_TBLPRODUCTOS_TBLCESTA(TBLPRODUCTOS_TBLCESTA entity)
		{
			this.SendPropertyChanging();
			entity.TBLPRODUCTOS = this;
		}
		
		private void detach_TBLPRODUCTOS_TBLCESTA(TBLPRODUCTOS_TBLCESTA entity)
		{
			this.SendPropertyChanging();
			entity.TBLPRODUCTOS = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBLPRODUCTOS_TBLCESTA")]
	public partial class TBLPRODUCTOS_TBLCESTA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TBLCESTA_ID;
		
		private int _TBLPRODUCTO_ID;
		
		private EntityRef<TBLCESTA> _TBLCESTA;
		
		private EntityRef<TBLPRODUCTOS> _TBLPRODUCTOS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTBLCESTA_IDChanging(int value);
    partial void OnTBLCESTA_IDChanged();
    partial void OnTBLPRODUCTO_IDChanging(int value);
    partial void OnTBLPRODUCTO_IDChanged();
    #endregion
		
		public TBLPRODUCTOS_TBLCESTA()
		{
			this._TBLCESTA = default(EntityRef<TBLCESTA>);
			this._TBLPRODUCTOS = default(EntityRef<TBLPRODUCTOS>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TBLCESTA_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TBLCESTA_ID
		{
			get
			{
				return this._TBLCESTA_ID;
			}
			set
			{
				if ((this._TBLCESTA_ID != value))
				{
					if (this._TBLCESTA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTBLCESTA_IDChanging(value);
					this.SendPropertyChanging();
					this._TBLCESTA_ID = value;
					this.SendPropertyChanged("TBLCESTA_ID");
					this.OnTBLCESTA_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TBLPRODUCTO_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TBLPRODUCTO_ID
		{
			get
			{
				return this._TBLPRODUCTO_ID;
			}
			set
			{
				if ((this._TBLPRODUCTO_ID != value))
				{
					if (this._TBLPRODUCTOS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTBLPRODUCTO_IDChanging(value);
					this.SendPropertyChanging();
					this._TBLPRODUCTO_ID = value;
					this.SendPropertyChanged("TBLPRODUCTO_ID");
					this.OnTBLPRODUCTO_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLCESTA_TBLPRODUCTOS_TBLCESTA", Storage="_TBLCESTA", ThisKey="TBLCESTA_ID", OtherKey="ID_CESTA", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public TBLCESTA TBLCESTA
		{
			get
			{
				return this._TBLCESTA.Entity;
			}
			set
			{
				TBLCESTA previousValue = this._TBLCESTA.Entity;
				if (((previousValue != value) 
							|| (this._TBLCESTA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBLCESTA.Entity = null;
						previousValue.TBLPRODUCTOS_TBLCESTA.Remove(this);
					}
					this._TBLCESTA.Entity = value;
					if ((value != null))
					{
						value.TBLPRODUCTOS_TBLCESTA.Add(this);
						this._TBLCESTA_ID = value.ID_CESTA;
					}
					else
					{
						this._TBLCESTA_ID = default(int);
					}
					this.SendPropertyChanged("TBLCESTA");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLPRODUCTOS_TBLPRODUCTOS_TBLCESTA", Storage="_TBLPRODUCTOS", ThisKey="TBLPRODUCTO_ID", OtherKey="ID_PRODUCTO", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public TBLPRODUCTOS TBLPRODUCTOS
		{
			get
			{
				return this._TBLPRODUCTOS.Entity;
			}
			set
			{
				TBLPRODUCTOS previousValue = this._TBLPRODUCTOS.Entity;
				if (((previousValue != value) 
							|| (this._TBLPRODUCTOS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBLPRODUCTOS.Entity = null;
						previousValue.TBLPRODUCTOS_TBLCESTA.Remove(this);
					}
					this._TBLPRODUCTOS.Entity = value;
					if ((value != null))
					{
						value.TBLPRODUCTOS_TBLCESTA.Add(this);
						this._TBLPRODUCTO_ID = value.ID_PRODUCTO;
					}
					else
					{
						this._TBLPRODUCTO_ID = default(int);
					}
					this.SendPropertyChanged("TBLPRODUCTOS");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBLROLES")]
	public partial class TBLROLES : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_ROL;
		
		private string _DESCRIPCION_ROL;
		
		private char _ESTADO_ROL;
		
		private EntitySet<TBLUSUARIOS> _TBLUSUARIOS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ROLChanging(int value);
    partial void OnID_ROLChanged();
    partial void OnDESCRIPCION_ROLChanging(string value);
    partial void OnDESCRIPCION_ROLChanged();
    partial void OnESTADO_ROLChanging(char value);
    partial void OnESTADO_ROLChanged();
    #endregion
		
		public TBLROLES()
		{
			this._TBLUSUARIOS = new EntitySet<TBLUSUARIOS>(new Action<TBLUSUARIOS>(this.attach_TBLUSUARIOS), new Action<TBLUSUARIOS>(this.detach_TBLUSUARIOS));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ROL", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_ROL
		{
			get
			{
				return this._ID_ROL;
			}
			set
			{
				if ((this._ID_ROL != value))
				{
					this.OnID_ROLChanging(value);
					this.SendPropertyChanging();
					this._ID_ROL = value;
					this.SendPropertyChanged("ID_ROL");
					this.OnID_ROLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION_ROL", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string DESCRIPCION_ROL
		{
			get
			{
				return this._DESCRIPCION_ROL;
			}
			set
			{
				if ((this._DESCRIPCION_ROL != value))
				{
					this.OnDESCRIPCION_ROLChanging(value);
					this.SendPropertyChanging();
					this._DESCRIPCION_ROL = value;
					this.SendPropertyChanged("DESCRIPCION_ROL");
					this.OnDESCRIPCION_ROLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO_ROL", DbType="Char(1) NOT NULL")]
		public char ESTADO_ROL
		{
			get
			{
				return this._ESTADO_ROL;
			}
			set
			{
				if ((this._ESTADO_ROL != value))
				{
					this.OnESTADO_ROLChanging(value);
					this.SendPropertyChanging();
					this._ESTADO_ROL = value;
					this.SendPropertyChanged("ESTADO_ROL");
					this.OnESTADO_ROLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLROLES_TBLUSUARIOS", Storage="_TBLUSUARIOS", ThisKey="ID_ROL", OtherKey="TBLROLE_ID")]
		public EntitySet<TBLUSUARIOS> TBLUSUARIOS
		{
			get
			{
				return this._TBLUSUARIOS;
			}
			set
			{
				this._TBLUSUARIOS.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBLUSUARIOS(TBLUSUARIOS entity)
		{
			this.SendPropertyChanging();
			entity.TBLROLES = this;
		}
		
		private void detach_TBLUSUARIOS(TBLUSUARIOS entity)
		{
			this.SendPropertyChanging();
			entity.TBLROLES = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBLSMTP")]
	public partial class TBLSMTP
	{
		
		private int _ID_EMAIL;
		
		private string _SMTP_EMAIL;
		
		private int _PUERTO_EMAIL;
		
		public TBLSMTP()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_EMAIL", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID_EMAIL
		{
			get
			{
				return this._ID_EMAIL;
			}
			set
			{
				if ((this._ID_EMAIL != value))
				{
					this._ID_EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SMTP_EMAIL", DbType="VarChar(70) NOT NULL", CanBeNull=false)]
		public string SMTP_EMAIL
		{
			get
			{
				return this._SMTP_EMAIL;
			}
			set
			{
				if ((this._SMTP_EMAIL != value))
				{
					this._SMTP_EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PUERTO_EMAIL", DbType="Int NOT NULL")]
		public int PUERTO_EMAIL
		{
			get
			{
				return this._PUERTO_EMAIL;
			}
			set
			{
				if ((this._PUERTO_EMAIL != value))
				{
					this._PUERTO_EMAIL = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBLCODRECUPERACION")]
	public partial class TBLCODRECUPERACION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_COD_RECUPERACION;
		
		private int _TBLUSUARIO_ID;
		
		private string _CODIGO_RECUPERACION;
		
		private System.DateTime _FECHA_CREACION_COD_RECUPERACION;
		
		private EntityRef<TBLUSUARIOS> _TBLUSUARIOS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_COD_RECUPERACIONChanging(int value);
    partial void OnID_COD_RECUPERACIONChanged();
    partial void OnTBLUSUARIO_IDChanging(int value);
    partial void OnTBLUSUARIO_IDChanged();
    partial void OnCODIGO_RECUPERACIONChanging(string value);
    partial void OnCODIGO_RECUPERACIONChanged();
    partial void OnFECHA_CREACION_COD_RECUPERACIONChanging(System.DateTime value);
    partial void OnFECHA_CREACION_COD_RECUPERACIONChanged();
    #endregion
		
		public TBLCODRECUPERACION()
		{
			this._TBLUSUARIOS = default(EntityRef<TBLUSUARIOS>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_COD_RECUPERACION", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_COD_RECUPERACION
		{
			get
			{
				return this._ID_COD_RECUPERACION;
			}
			set
			{
				if ((this._ID_COD_RECUPERACION != value))
				{
					this.OnID_COD_RECUPERACIONChanging(value);
					this.SendPropertyChanging();
					this._ID_COD_RECUPERACION = value;
					this.SendPropertyChanged("ID_COD_RECUPERACION");
					this.OnID_COD_RECUPERACIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TBLUSUARIO_ID", DbType="Int NOT NULL")]
		public int TBLUSUARIO_ID
		{
			get
			{
				return this._TBLUSUARIO_ID;
			}
			set
			{
				if ((this._TBLUSUARIO_ID != value))
				{
					if (this._TBLUSUARIOS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTBLUSUARIO_IDChanging(value);
					this.SendPropertyChanging();
					this._TBLUSUARIO_ID = value;
					this.SendPropertyChanged("TBLUSUARIO_ID");
					this.OnTBLUSUARIO_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_RECUPERACION", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string CODIGO_RECUPERACION
		{
			get
			{
				return this._CODIGO_RECUPERACION;
			}
			set
			{
				if ((this._CODIGO_RECUPERACION != value))
				{
					this.OnCODIGO_RECUPERACIONChanging(value);
					this.SendPropertyChanging();
					this._CODIGO_RECUPERACION = value;
					this.SendPropertyChanged("CODIGO_RECUPERACION");
					this.OnCODIGO_RECUPERACIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_CREACION_COD_RECUPERACION", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_CREACION_COD_RECUPERACION
		{
			get
			{
				return this._FECHA_CREACION_COD_RECUPERACION;
			}
			set
			{
				if ((this._FECHA_CREACION_COD_RECUPERACION != value))
				{
					this.OnFECHA_CREACION_COD_RECUPERACIONChanging(value);
					this.SendPropertyChanging();
					this._FECHA_CREACION_COD_RECUPERACION = value;
					this.SendPropertyChanged("FECHA_CREACION_COD_RECUPERACION");
					this.OnFECHA_CREACION_COD_RECUPERACIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLUSUARIOS_TBLCODRECUPERACION", Storage="_TBLUSUARIOS", ThisKey="TBLUSUARIO_ID", OtherKey="ID_USUARIO", IsForeignKey=true)]
		public TBLUSUARIOS TBLUSUARIOS
		{
			get
			{
				return this._TBLUSUARIOS.Entity;
			}
			set
			{
				TBLUSUARIOS previousValue = this._TBLUSUARIOS.Entity;
				if (((previousValue != value) 
							|| (this._TBLUSUARIOS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBLUSUARIOS.Entity = null;
						previousValue.TBLCODRECUPERACION.Remove(this);
					}
					this._TBLUSUARIOS.Entity = value;
					if ((value != null))
					{
						value.TBLCODRECUPERACION.Add(this);
						this._TBLUSUARIO_ID = value.ID_USUARIO;
					}
					else
					{
						this._TBLUSUARIO_ID = default(int);
					}
					this.SendPropertyChanged("TBLUSUARIOS");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBLUSUARIOS")]
	public partial class TBLUSUARIOS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_USUARIO;
		
		private int _TBLROLE_ID;
		
		private string _USU_USUARIO;
		
		private string _PASS_USUARIO;
		
		private string _NOMBRE_USUARIO;
		
		private string _APELLIDO_USUARIO;
		
		private string _EMAIL_USUARIO;
		
		private System.DateTime _FECHA_CREACION_USUARIO;
		
		private string _FOTO_PATH_USUARIO;
		
		private string _TELEFONO_USUARIO;
		
		private char _ESTADO_USUARIO;
		
		private EntitySet<TBLCODRECUPERACION> _TBLCODRECUPERACION;
		
		private EntityRef<TBLROLES> _TBLROLES;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_USUARIOChanging(int value);
    partial void OnID_USUARIOChanged();
    partial void OnTBLROLE_IDChanging(int value);
    partial void OnTBLROLE_IDChanged();
    partial void OnUSU_USUARIOChanging(string value);
    partial void OnUSU_USUARIOChanged();
    partial void OnPASS_USUARIOChanging(string value);
    partial void OnPASS_USUARIOChanged();
    partial void OnNOMBRE_USUARIOChanging(string value);
    partial void OnNOMBRE_USUARIOChanged();
    partial void OnAPELLIDO_USUARIOChanging(string value);
    partial void OnAPELLIDO_USUARIOChanged();
    partial void OnEMAIL_USUARIOChanging(string value);
    partial void OnEMAIL_USUARIOChanged();
    partial void OnFECHA_CREACION_USUARIOChanging(System.DateTime value);
    partial void OnFECHA_CREACION_USUARIOChanged();
    partial void OnFOTO_PATH_USUARIOChanging(string value);
    partial void OnFOTO_PATH_USUARIOChanged();
    partial void OnTELEFONO_USUARIOChanging(string value);
    partial void OnTELEFONO_USUARIOChanged();
    partial void OnESTADO_USUARIOChanging(char value);
    partial void OnESTADO_USUARIOChanged();
    #endregion
		
		public TBLUSUARIOS()
		{
			this._TBLCODRECUPERACION = new EntitySet<TBLCODRECUPERACION>(new Action<TBLCODRECUPERACION>(this.attach_TBLCODRECUPERACION), new Action<TBLCODRECUPERACION>(this.detach_TBLCODRECUPERACION));
			this._TBLROLES = default(EntityRef<TBLROLES>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_USUARIO
		{
			get
			{
				return this._ID_USUARIO;
			}
			set
			{
				if ((this._ID_USUARIO != value))
				{
					this.OnID_USUARIOChanging(value);
					this.SendPropertyChanging();
					this._ID_USUARIO = value;
					this.SendPropertyChanged("ID_USUARIO");
					this.OnID_USUARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TBLROLE_ID", DbType="Int NOT NULL")]
		public int TBLROLE_ID
		{
			get
			{
				return this._TBLROLE_ID;
			}
			set
			{
				if ((this._TBLROLE_ID != value))
				{
					if (this._TBLROLES.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTBLROLE_IDChanging(value);
					this.SendPropertyChanging();
					this._TBLROLE_ID = value;
					this.SendPropertyChanged("TBLROLE_ID");
					this.OnTBLROLE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USU_USUARIO", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string USU_USUARIO
		{
			get
			{
				return this._USU_USUARIO;
			}
			set
			{
				if ((this._USU_USUARIO != value))
				{
					this.OnUSU_USUARIOChanging(value);
					this.SendPropertyChanging();
					this._USU_USUARIO = value;
					this.SendPropertyChanged("USU_USUARIO");
					this.OnUSU_USUARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASS_USUARIO", DbType="VarChar(300) NOT NULL", CanBeNull=false)]
		public string PASS_USUARIO
		{
			get
			{
				return this._PASS_USUARIO;
			}
			set
			{
				if ((this._PASS_USUARIO != value))
				{
					this.OnPASS_USUARIOChanging(value);
					this.SendPropertyChanging();
					this._PASS_USUARIO = value;
					this.SendPropertyChanged("PASS_USUARIO");
					this.OnPASS_USUARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_USUARIO", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string NOMBRE_USUARIO
		{
			get
			{
				return this._NOMBRE_USUARIO;
			}
			set
			{
				if ((this._NOMBRE_USUARIO != value))
				{
					this.OnNOMBRE_USUARIOChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE_USUARIO = value;
					this.SendPropertyChanged("NOMBRE_USUARIO");
					this.OnNOMBRE_USUARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDO_USUARIO", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string APELLIDO_USUARIO
		{
			get
			{
				return this._APELLIDO_USUARIO;
			}
			set
			{
				if ((this._APELLIDO_USUARIO != value))
				{
					this.OnAPELLIDO_USUARIOChanging(value);
					this.SendPropertyChanging();
					this._APELLIDO_USUARIO = value;
					this.SendPropertyChanged("APELLIDO_USUARIO");
					this.OnAPELLIDO_USUARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL_USUARIO", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string EMAIL_USUARIO
		{
			get
			{
				return this._EMAIL_USUARIO;
			}
			set
			{
				if ((this._EMAIL_USUARIO != value))
				{
					this.OnEMAIL_USUARIOChanging(value);
					this.SendPropertyChanging();
					this._EMAIL_USUARIO = value;
					this.SendPropertyChanged("EMAIL_USUARIO");
					this.OnEMAIL_USUARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_CREACION_USUARIO", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_CREACION_USUARIO
		{
			get
			{
				return this._FECHA_CREACION_USUARIO;
			}
			set
			{
				if ((this._FECHA_CREACION_USUARIO != value))
				{
					this.OnFECHA_CREACION_USUARIOChanging(value);
					this.SendPropertyChanging();
					this._FECHA_CREACION_USUARIO = value;
					this.SendPropertyChanged("FECHA_CREACION_USUARIO");
					this.OnFECHA_CREACION_USUARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOTO_PATH_USUARIO", DbType="VarChar(300)")]
		public string FOTO_PATH_USUARIO
		{
			get
			{
				return this._FOTO_PATH_USUARIO;
			}
			set
			{
				if ((this._FOTO_PATH_USUARIO != value))
				{
					this.OnFOTO_PATH_USUARIOChanging(value);
					this.SendPropertyChanging();
					this._FOTO_PATH_USUARIO = value;
					this.SendPropertyChanged("FOTO_PATH_USUARIO");
					this.OnFOTO_PATH_USUARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO_USUARIO", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string TELEFONO_USUARIO
		{
			get
			{
				return this._TELEFONO_USUARIO;
			}
			set
			{
				if ((this._TELEFONO_USUARIO != value))
				{
					this.OnTELEFONO_USUARIOChanging(value);
					this.SendPropertyChanging();
					this._TELEFONO_USUARIO = value;
					this.SendPropertyChanged("TELEFONO_USUARIO");
					this.OnTELEFONO_USUARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO_USUARIO", DbType="Char(1) NOT NULL")]
		public char ESTADO_USUARIO
		{
			get
			{
				return this._ESTADO_USUARIO;
			}
			set
			{
				if ((this._ESTADO_USUARIO != value))
				{
					this.OnESTADO_USUARIOChanging(value);
					this.SendPropertyChanging();
					this._ESTADO_USUARIO = value;
					this.SendPropertyChanged("ESTADO_USUARIO");
					this.OnESTADO_USUARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLUSUARIOS_TBLCODRECUPERACION", Storage="_TBLCODRECUPERACION", ThisKey="ID_USUARIO", OtherKey="TBLUSUARIO_ID")]
		public EntitySet<TBLCODRECUPERACION> TBLCODRECUPERACION
		{
			get
			{
				return this._TBLCODRECUPERACION;
			}
			set
			{
				this._TBLCODRECUPERACION.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLROLES_TBLUSUARIOS", Storage="_TBLROLES", ThisKey="TBLROLE_ID", OtherKey="ID_ROL", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public TBLROLES TBLROLES
		{
			get
			{
				return this._TBLROLES.Entity;
			}
			set
			{
				TBLROLES previousValue = this._TBLROLES.Entity;
				if (((previousValue != value) 
							|| (this._TBLROLES.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBLROLES.Entity = null;
						previousValue.TBLUSUARIOS.Remove(this);
					}
					this._TBLROLES.Entity = value;
					if ((value != null))
					{
						value.TBLUSUARIOS.Add(this);
						this._TBLROLE_ID = value.ID_ROL;
					}
					else
					{
						this._TBLROLE_ID = default(int);
					}
					this.SendPropertyChanged("TBLROLES");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBLCODRECUPERACION(TBLCODRECUPERACION entity)
		{
			this.SendPropertyChanging();
			entity.TBLUSUARIOS = this;
		}
		
		private void detach_TBLCODRECUPERACION(TBLCODRECUPERACION entity)
		{
			this.SendPropertyChanging();
			entity.TBLUSUARIOS = null;
		}
	}
}
#pragma warning restore 1591
